"""
Builds supabase/seed_market_trends.sql from the Redfin Data Center.

Redfin publishes no REST API. What it does publish -- free, and without a key --
is the Data Center: aggregated market-trend datasets as compressed TSV on S3,
refreshed the third Friday of each month. This pulls the zip-code tracker and
keeps only the rows this app can use.

The source file is ~1.4GB compressed and decompresses to several GB, so it is
streamed and filtered in flight; nothing large is ever written to disk. Expect
this to take a while on a slow connection -- it is downloading the whole file
either way, it just doesn't keep it.

Only the "All Residential" aggregate is kept (the file also carries separate
Condo/Townhouse/Single-Family/Multi-Family series per zip-month, which would
multiply the row count fivefold for no benefit here), and only for the zips
that actually appear in the seeded listings.

Run after the listings exist, since the zip list is derived from them:

    python scripts/process_realtor_data.py
    python scripts/process_redfin_market_data.py
    npx supabase db reset
"""

import gzip
import json
import os
import urllib.request

REDFIN_URL = (
    "https://redfin-public-data.s3.us-west-2.amazonaws.com"
    "/redfin_market_tracker/zip_code_market_tracker.tsv000.gz"
)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SEED_DATA_PATH = os.path.join(REPO_ROOT, "scripts", "seed_data.json")
SQL_OUTPUT_PATH = os.path.join(REPO_ROOT, "supabase", "seed_market_trends.sql")

# The three hand-written listings in seed.sql (ids 1-3), which are not in
# seed_data.json but still need market context on their detail pages.
SEED_SQL_ZIPS = {"78701", "78702", "78704"}

# Column positions in the Redfin TSV. Named here rather than inline so a
# reordering upstream fails loudly at the header check below.
COL = {
    "period_begin": 0,
    "region": 7,
    "state_code": 10,
    "property_type": 11,
    "median_sale_price": 13,
    "median_sale_price_yoy": 15,
    "median_ppsf": 19,
    "homes_sold": 25,
    "new_listings": 31,
    "inventory": 34,
    "median_dom": 40,
}


def target_zips():
    with open(SEED_DATA_PATH, encoding="utf-8") as fh:
        listings = json.load(fh)
    zips = {str(row["zip_code"]).strip() for row in listings if row.get("zip_code")}
    return zips | SEED_SQL_ZIPS


def sql_number(raw):
    """Redfin leaves missing metrics empty; those become NULL rather than 0."""
    raw = raw.strip().strip('"')
    if not raw:
        return "NULL"
    try:
        return repr(float(raw))
    except ValueError:
        return "NULL"


def sql_int(raw):
    value = sql_number(raw)
    return "NULL" if value == "NULL" else str(int(float(value)))


def main():
    wanted = target_zips()
    print(f"Collecting market history for {len(wanted)} zip codes...")

    rows = []
    request = urllib.request.Request(REDFIN_URL, headers={"User-Agent": "dwellingly-seed/1.0"})

    with urllib.request.urlopen(request) as response:
        with gzip.open(response, mode="rt", encoding="utf-8", errors="replace") as stream:
            header = next(stream).rstrip("\n").split("\t")
            header = [h.strip().strip('"').upper() for h in header]
            for name, index in COL.items():
                expected = name.upper()
                if index >= len(header) or header[index] != expected:
                    raise SystemExit(
                        f"Redfin column layout changed: expected {expected} at "
                        f"index {index}, found {header[index] if index < len(header) else 'nothing'}. "
                        "Update COL before trusting this output."
                    )

            for line in stream:
                fields = line.rstrip("\n").split("\t")
                if len(fields) <= COL["median_dom"]:
                    continue
                if fields[COL["state_code"]].strip('"') != "TX":
                    continue
                if fields[COL["property_type"]].strip('"') != "All Residential":
                    continue
                zip_code = fields[COL["region"]].strip('"').replace("Zip Code: ", "")
                if zip_code not in wanted:
                    continue
                rows.append((zip_code, fields))

    rows.sort(key=lambda r: (r[0], r[1][COL["period_begin"]]))
    print(f"Kept {len(rows)} zip-month observations.")

    covered = {zip_code for zip_code, _ in rows}
    missing = sorted(wanted - covered)
    if missing:
        # Not fatal: small or new zips genuinely have no Redfin coverage, and
        # the detail page degrades to "no market data" for those.
        print(f"No Redfin coverage for {len(missing)} zips: {', '.join(missing)}")

    with open(SQL_OUTPUT_PATH, "w", encoding="utf-8") as out:
        out.write("-- Generated by scripts/process_redfin_market_data.py\n")
        out.write("-- Source: Redfin Data Center (https://www.redfin.com/news/data-center/)\n")
        out.write("-- Aggregated monthly market data per zip code. Area-level only --\n")
        out.write("-- this is never a specific property's sale history.\n\n")
        out.write("TRUNCATE TABLE public.market_trends;\n\n")

        for zip_code, f in rows:
            out.write(
                "INSERT INTO public.market_trends "
                "(zip_code, period_begin, median_sale_price, median_ppsf, "
                "homes_sold, new_listings, inventory, median_dom, median_sale_price_yoy) VALUES ("
                f"'{zip_code}', "
                f"'{f[COL['period_begin']].strip(chr(34))}', "
                f"{sql_number(f[COL['median_sale_price']])}, "
                f"{sql_number(f[COL['median_ppsf']])}, "
                f"{sql_int(f[COL['homes_sold']])}, "
                f"{sql_int(f[COL['new_listings']])}, "
                f"{sql_int(f[COL['inventory']])}, "
                f"{sql_int(f[COL['median_dom']])}, "
                f"{sql_number(f[COL['median_sale_price_yoy']])}"
                ");\n"
            )

    print(f"Wrote {SQL_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
