-- ============================================================================
-- DWELLINGLY.AI / NEXHOMEAGENT AI - PGVECTOR INTEGRATION & RPC SEARCH
-- Migration: 20250101000001_enable_pgvector.sql
-- Embeddings Dimension: 768 (Google GenAI text-embedding-004)
-- ============================================================================

-- 1. ENABLE VECTOR EXTENSION
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. PROPERTY EMBEDDINGS TABLE
CREATE TABLE public.property_vectors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT UNIQUE REFERENCES public.properties(id) ON DELETE CASCADE,
  content_summary TEXT NOT NULL, -- Textual representations used to build embedding
  embedding vector(768) NOT NULL, -- Matched to Google text-embedding-004 output dimension
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER tr_property_vectors_updated_at
  BEFORE UPDATE ON public.property_vectors
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 3. HNSW INDEX FOR HIGH-PERFORMANCE COSINE VECTOR SIMILARITY SEARCH
-- HNSW provides sub-millisecond search latency compared to IVFFlat.
CREATE INDEX idx_property_vectors_hnsw_cosine
  ON public.property_vectors
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- 4. RPC STORED PROCEDURE: HYBRID SEMANTIC VECTOR SIMILARITY SEARCH
CREATE OR REPLACE FUNCTION public.match_properties(
  query_embedding vector(768),
  match_threshold FLOAT DEFAULT 0.3,
  match_count INT DEFAULT 10,
  filter_city TEXT DEFAULT NULL,
  filter_min_price NUMERIC DEFAULT NULL,
  filter_max_price NUMERIC DEFAULT NULL,
  filter_min_bedrooms INT DEFAULT NULL,
  filter_min_bathrooms NUMERIC DEFAULT NULL
)
RETURNS TABLE (
  property_id BIGINT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  price NUMERIC,
  bedrooms INT,
  bathrooms NUMERIC,
  square_feet INT,
  description TEXT,
  features JSONB,
  photos JSONB,
  content_summary TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id AS property_id,
    p.address,
    p.city,
    p.state,
    p.zip_code,
    p.price,
    p.bedrooms,
    p.bathrooms,
    p.square_feet,
    p.description,
    p.features,
    p.photos,
    pv.content_summary,
    (1 - (pv.embedding <=> query_embedding))::FLOAT AS similarity
  FROM public.property_vectors pv
  JOIN public.properties p ON p.id = pv.property_id
  WHERE
    p.status = 'active'
    AND (1 - (pv.embedding <=> query_embedding)) >= match_threshold
    AND (filter_city IS NULL OR LOWER(p.city) = LOWER(filter_city))
    AND (filter_min_price IS NULL OR p.price >= filter_min_price)
    AND (filter_max_price IS NULL OR p.price <= filter_max_price)
    AND (filter_min_bedrooms IS NULL OR p.bedrooms >= filter_min_bedrooms)
    AND (filter_min_bathrooms IS NULL OR p.bathrooms >= filter_min_bathrooms)
  ORDER BY pv.embedding <=> query_embedding ASC
  LIMIT match_count;
END;
$$;