-- ============================================================================
-- DWELLINGLY.AI / NEXHOMEAGENT AI - CORE DATABASE MIGRATION
-- Migration: 20250101000000_init_schema.sql
-- Stack Target: Supabase / PostgreSQL 15+
-- ============================================================================

-- 1. EXTENSIONS SETUP
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm"; -- For text search fuzzy matching

-- 2. AUTOMATED UPDATED_AT TIMESTAMP TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- 3. PROFILES TABLE (Extends auth.users)
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL DEFAULT 'buyer' CHECK (role IN ('buyer', 'seller', 'agent', 'admin')),
  phone TEXT,
  avatar_url TEXT,
  metadata JSONB DEFAULT '{}'::jsonb NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER tr_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 4. AUTOMATIC PROFILE CREATION TRIGGER FROM AUTH SIGNUP
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, role, avatar_url)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', 'New User'),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'role', 'buyer'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 5. PROPERTIES TABLE
CREATE TABLE public.properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  zip_code TEXT NOT NULL,
  latitude NUMERIC(10, 7),
  longitude NUMERIC(10, 7),
  price NUMERIC(18, 2) NOT NULL CHECK (price >= 0),
  bedrooms INT NOT NULL CHECK (bedrooms >= 0),
  bathrooms NUMERIC(3, 1) NOT NULL CHECK (bathrooms >= 0),
  square_feet INT CHECK (square_feet >= 0),
  property_type TEXT DEFAULT 'single_family' CHECK (property_type IN ('single_family', 'condo', 'townhouse', 'multi_family', 'land')),
  description TEXT NOT NULL,
  features JSONB DEFAULT '{}'::jsonb NOT NULL, -- e.g. {"hasPool": true, "garageSpaces": 2, "yearBuilt": 2021}
  photos JSONB DEFAULT '[]'::jsonb NOT NULL,   -- Array of public image URLs
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'pending', 'sold', 'draft', 'archived')),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER tr_properties_updated_at
  BEFORE UPDATE ON public.properties
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 6. COMPARATIVE MARKET ANALYSIS (CMA) REPORTS
CREATE TABLE public.cma_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  estimated_valuation NUMERIC(18, 2) NOT NULL,
  valuation_range_low NUMERIC(18, 2) NOT NULL,
  valuation_range_high NUMERIC(18, 2) NOT NULL,
  comparable_property_ids BIGINT[] DEFAULT '{}',
  report_data JSONB NOT NULL, -- Deep JSON from Gemini 3 Pro reasoning engine
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 7. OFFERS TABLE
CREATE TABLE public.offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  buyer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  offer_amount NUMERIC(18, 2) NOT NULL CHECK (offer_amount > 0),
  earnest_money NUMERIC(18, 2) CHECK (earnest_money >= 0),
  contingencies JSONB DEFAULT '[]'::jsonb NOT NULL, -- e.g. ["inspection", "financing", "appraisal"]
  status TEXT DEFAULT 'submitted' CHECK (status IN ('submitted', 'countered', 'accepted', 'rejected', 'withdrawn')),
  contract_url TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER tr_offers_updated_at
  BEFORE UPDATE ON public.offers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 8. VIEWINGS / APPOINTMENTS TABLE
CREATE TABLE public.viewings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  scheduled_at TIMESTAMPTZ NOT NULL,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'confirmed', 'completed', 'cancelled')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE TRIGGER tr_viewings_updated_at
  BEFORE UPDATE ON public.viewings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- 9. FAVORITES TABLE (Composite Primary Key)
CREATE TABLE public.favorites (
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  property_id BIGINT REFERENCES public.properties(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  PRIMARY KEY (user_id, property_id)
);

-- 10. B-TREE & GIN INDEXES FOR QUERY OPTIMIZATION
CREATE INDEX idx_properties_status_price ON public.properties(status, price);
CREATE INDEX idx_properties_city_state ON public.properties(city, state);
CREATE INDEX idx_properties_bedrooms_bathrooms ON public.properties(bedrooms, bathrooms);
CREATE INDEX idx_properties_owner_id ON public.properties(owner_id);
CREATE INDEX idx_properties_features_gin ON public.properties USING GIN (features);

CREATE INDEX idx_cma_reports_property_user ON public.cma_reports(property_id, user_id);
CREATE INDEX idx_offers_property_buyer ON public.offers(property_id, buyer_id);
CREATE INDEX idx_offers_status ON public.offers(status);
CREATE INDEX idx_viewings_user_scheduled ON public.viewings(user_id, scheduled_at);