-- ============================================================================
-- DWELLINGLY.AI / NEXHOMEAGENT AI - DATA API ROLE GRANTS
-- Migration: 20260730000001_grant_data_api_roles.sql
--
-- This Supabase version no longer auto-exposes tables created by migrations to
-- the Data API roles, so `anon` / `authenticated` / `service_role` were left
-- with only REFERENCES/TRIGGER/TRUNCATE and every PostgREST query failed with
-- `42501 permission denied for table ...`.
--
-- GRANTs and RLS are two independent layers: the GRANT decides whether the role
-- may touch the table at all, RLS then decides which rows. The grants below are
-- deliberately scoped to match the policies in 20240101000002_rls_policies.sql
-- rather than blanket-granting the schema -- if a table has no policy for an
-- operation, the role gets no privilege for it either.
--
-- Identity columns (GENERATED BY DEFAULT AS IDENTITY) do not require privileges
-- on their backing sequence, so no sequence grants are needed here.
-- ============================================================================

-- Both Data API roles need to resolve objects in the schema first.
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- ----------------------------------------------------------------------------
-- PROFILES -- SELECT + UPDATE own row. Rows are created by the
-- handle_new_user() SECURITY DEFINER trigger, so no INSERT grant.
-- ----------------------------------------------------------------------------
GRANT SELECT, UPDATE ON public.profiles TO authenticated;

-- ----------------------------------------------------------------------------
-- PROPERTIES -- readable by anonymous visitors (policy is TO public, active
-- listings only); writes restricted to owners with a seller/agent/admin role.
-- ----------------------------------------------------------------------------
GRANT SELECT ON public.properties TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.properties TO authenticated;

-- ----------------------------------------------------------------------------
-- PROPERTY_VECTORS -- readable by everyone (policy is TO public); inserted by
-- the owning seller. Note match_properties() is SECURITY DEFINER and therefore
-- already worked without these grants.
-- ----------------------------------------------------------------------------
GRANT SELECT ON public.property_vectors TO anon, authenticated;
GRANT INSERT ON public.property_vectors TO authenticated;

-- ----------------------------------------------------------------------------
-- CMA_REPORTS -- users read their own reports and reports on their listings,
-- and insert reports attributed to themselves. No update/delete policy exists.
-- ----------------------------------------------------------------------------
GRANT SELECT, INSERT ON public.cma_reports TO authenticated;

-- ----------------------------------------------------------------------------
-- OFFERS -- buyers submit; buyers and listing owners read and update status.
-- No delete policy exists (offers are withdrawn via status, not removed).
-- ----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON public.offers TO authenticated;

-- ----------------------------------------------------------------------------
-- VIEWINGS -- users schedule their own tours; users and listing owners read and
-- reschedule/cancel via status.
-- ----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON public.viewings TO authenticated;

-- ----------------------------------------------------------------------------
-- FAVORITES -- users add, read, and remove their own favorites. No update
-- policy exists (the toggle is an insert/delete pair).
-- ----------------------------------------------------------------------------
GRANT SELECT, INSERT, DELETE ON public.favorites TO authenticated;

-- ----------------------------------------------------------------------------
-- SERVICE_ROLE -- trusted server-side key used by scripts/seed.ts and
-- scripts/generate_embeddings.ts. It carries BYPASSRLS, but still needs table
-- privileges to reach the tables at all.
-- ----------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.profiles,
  public.properties,
  public.property_vectors,
  public.cma_reports,
  public.offers,
  public.viewings,
  public.favorites
TO service_role;

-- ----------------------------------------------------------------------------
-- Keep future tables in this schema from silently repeating the same problem.
-- Applies only to objects created later by the role running migrations.
-- ----------------------------------------------------------------------------
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO service_role;
