-- ============================================================================
-- DWELLINGLY.AI - DEAL COLLABORATION
-- Migration: 20260804000004_offer_messages_and_counters.sql
-- Backs the Agent/Seller Collaboration Hub: a message thread between the two
-- parties to an offer, plus the counter-offer terms the `countered` status
-- already implied but had nowhere to record.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. MESSAGE THREAD
-- Hangs off the offer rather than the property: a property can carry several
-- competing offers, and those buyers must never see each other's negotiation.
-- ----------------------------------------------------------------------------
CREATE TABLE public.offer_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id BIGINT NOT NULL REFERENCES public.offers(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  body TEXT NOT NULL CHECK (length(trim(body)) > 0),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX idx_offer_messages_offer_created
  ON public.offer_messages(offer_id, created_at);

ALTER TABLE public.offer_messages ENABLE ROW LEVEL SECURITY;

-- Both sides of the deal -- the buyer who made the offer, and the owner of the
-- listing it was made on -- can read and post. Mirrors the offers SELECT policy.
CREATE POLICY "Deal participants can read the thread"
  ON public.offer_messages FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.offers o
      LEFT JOIN public.properties p ON p.id = o.property_id
      WHERE o.id = offer_id
        AND (o.buyer_id = auth.uid() OR p.owner_id = auth.uid())
    )
  );

-- `sender_id = auth.uid()` stops a participant posting as the other party.
CREATE POLICY "Deal participants can post to the thread"
  ON public.offer_messages FOR INSERT
  TO authenticated
  WITH CHECK (
    sender_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM public.offers o
      LEFT JOIN public.properties p ON p.id = o.property_id
      WHERE o.id = offer_id
        AND (o.buyer_id = auth.uid() OR p.owner_id = auth.uid())
    )
  );

-- No UPDATE or DELETE policy: a negotiation record shouldn't be editable after
-- the fact. Grants below are deliberately narrowed to match.

-- This Supabase project does not auto-expose new tables to the Data API, so a
-- policy alone isn't enough -- without the GRANT every query fails with
-- `42501 permission denied`. See CLAUDE.md "New tables need an explicit GRANT".
GRANT SELECT, INSERT ON public.offer_messages TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.offer_messages_id_seq TO authenticated;

-- ----------------------------------------------------------------------------
-- 2. REALTIME
-- The thread is the app's only live surface; everything else refreshes via
-- revalidatePath. Realtime still respects RLS, so a subscriber only receives
-- rows their SELECT policy would have returned.
-- ----------------------------------------------------------------------------
ALTER PUBLICATION supabase_realtime ADD TABLE public.offer_messages;

-- ----------------------------------------------------------------------------
-- 3. COUNTER-OFFER TERMS
-- `offers.status` has always accepted 'countered', but there was nowhere to
-- record what was actually countered with, so the status carried no meaning.
-- ----------------------------------------------------------------------------
ALTER TABLE public.offers
  ADD COLUMN IF NOT EXISTS counter_amount NUMERIC(18, 2) CHECK (counter_amount > 0);

-- Seller-funded credit to the buyer (repair allowance, closing costs). Stored
-- positive; it reduces the seller's net, and is displayed as a negative.
ALTER TABLE public.offers
  ADD COLUMN IF NOT EXISTS counter_concession NUMERIC(18, 2) CHECK (counter_concession >= 0);

ALTER TABLE public.offers
  ADD COLUMN IF NOT EXISTS counter_notes TEXT;

ALTER TABLE public.offers
  ADD COLUMN IF NOT EXISTS countered_at TIMESTAMPTZ;
